Repository HathorNetwork/hathor-core, pull requests merged in 2023-06, with the labels that each got.

#642 refactor: Add common Hathor types
  hathor/manager.py
  hathor/transaction/base_transaction.py
  hathor/transaction/transaction.py
  hathor/types.py
  hathor/util.py
Labels: refactor

#646 tests: Skip flaky event tests
  tests/event/test_simulation.py
Labels: tests

#651 chore: improve progress function
  hathor/cli/db_export.py
  hathor/cli/db_import.py
  hathor/indexes/manager.py
  hathor/indexes/partial_rocksdb_tips_index.py
  hathor/util.py
Labels: enhancement

#640 refactor(builder): Build IndexesManager on builders
  hathor/builder/builder.py
  hathor/builder/cli_builder.py
  hathor/indexes/manager.py
  hathor/metrics.py
  hathor/transaction/storage/cache_storage.py
  hathor/transaction/storage/memory_storage.py
  hathor/transaction/storage/rocksdb_storage.py
  hathor/transaction/storage/transaction_storage.py
  tests/others/test_metrics.py
  tests/tx/test_cache_storage.py
  tests/tx/test_indexes4.py
  tests/tx/test_tx.py
  tests/tx/test_tx_storage.py
  tests/unittest.py
Labels: refactor

#662 refactor(init): Remove duplicate code and simplify full verification method
  hathor/manager.py
Labels: refactor

#666 fix: settings initialization
  hathor/cli/run_node.py
Labels: bug

#664 refactor: Change HathorManager.on_new_tx() to accept only fully validated transactions
  hathor/manager.py
Labels: refactor

#669 tests: Do not update time by default on BaseTransaction.resolve()
  hathor/transaction/base_transaction.py
Labels: tests

#647 fix(events): fix bugs in the event stream and improve tests
  hathor/builder/builder.py
  hathor/event/event_manager.py
  hathor/event/model/base_event.py
  hathor/event/model/event_data.py
  hathor/event/model/event_type.py
  hathor/event/websocket/factory.py
  hathor/event/websocket/protocol.py
  tests/event/event_simulation_tester.py
  tests/event/test_event_manager.py
  tests/event/test_event_reorg.py
  tests/event/test_event_simulation_responses.py
  tests/event/test_simulation.py
  tests/event/test_tx_metadata.py
  tests/event/websocket/test_protocol.py
  tests/unittest.py
Labels: bug, tests

#649 tests(events): migrate flaky event simulation tests to new format
  hathor/simulator/miner/dummy_miner.py
  hathor/simulator/simulator.py
  tests/event/event_simulation_tester.py
  tests/event/test_event_simulation_scenarios.py
  tests/event/test_simulation.py
Labels: tests

#660 tests(feature-activation): implement reorg test
  hathor/feature_activation/feature_service.py
  hathor/manager.py
  hathor/mining/block_template.py
  hathor/simulator/miner/geometric_miner.py
  tests/feature_activation/test_feature_service.py
  tests/feature_activation/test_feature_simulation.py
Labels: tests

#652 refactor(events): improve events during the load phase
  hathor/event/event_manager.py
  hathor/event/model/event_type.py
  hathor/event/storage/event_storage.py
  hathor/event/storage/memory_storage.py
  hathor/event/storage/rocksdb_storage.py
  hathor/manager.py
  hathor/pubsub.py
  tests/event/test_event_simulation_scenarios.py
  tests/event/test_event_storage.py
Labels: enhancement
