Repository HathorNetwork/hathor-core, pull requests merged in 2023-11, with the labels that each got.

#801 refactor(settings): change daa to use injected settings
  hathor/builder/builder.py
  hathor/builder/cli_builder.py
  hathor/cli/events_simulator/scenario.py
  hathor/cli/mining.py
  hathor/daa.py
  hathor/manager.py
  hathor/p2p/resources/mining_info.py
  hathor/simulator/simulator.py
  hathor/simulator/tx_generator.py
  hathor/stratum/stratum.py
  hathor/transaction/resources/create_tx.py
  hathor/verification/block_verifier.py
  hathor/verification/transaction_verifier.py
  hathor/verification/verification_service.py
  hathor/verification/vertex_verifier.py
  hathor/wallet/resources/nano_contracts/execute.py
  hathor/wallet/resources/send_tokens.py
  hathor/wallet/resources/sign_tx.py
  tests/resources/wallet/test_thin_wallet.py
  tests/simulation/test_simulator.py
  tests/tx/test_block.py
  tests/tx/test_blockchain.py
  tests/tx/test_genesis.py
  tests/tx/test_tx.py
  tests/tx/test_tx_deserialization.py
  tests/unittest.py
Labels: refactor

#802 refactor(daa): remove global daa test mode
  hathor/builder/cli_builder.py
  hathor/daa.py
  hathor/p2p/peer_id.py
  hathor/simulator/simulator.py
  tests/p2p/test_split_brain.py
  tests/resources/base_resource.py
  tests/resources/transaction/test_create_tx.py
  tests/resources/wallet/test_send_tokens.py
  tests/tx/test_blockchain.py
  tests/tx/test_cache_storage.py
  tests/tx/test_genesis.py
  tests/tx/test_tx.py
  tests/tx/test_tx_storage.py
  tests/unittest.py
Labels: refactor

#803 refactor(cpu-mining): create CpuMiningService
  hathor/builder/builder.py
  hathor/builder/cli_builder.py
  hathor/cli/mining.py
  hathor/cli/multisig_spend.py
  hathor/cli/twin_tx.py
  hathor/manager.py
  hathor/mining/cpu_mining_service.py
  hathor/simulator/patches.py
  hathor/simulator/simulator.py
  hathor/transaction/base_transaction.py
  hathor/transaction/token_creation_tx.py
  hathor/wallet/resources/nano_contracts/execute.py
  hathor/wallet/resources/send_tokens.py
  hathor/wallet/resources/sign_tx.py
  hathor/wallet/resources/thin_wallet/send_tokens.py
  tests/cli/test_multisig_spend.py
  tests/consensus/test_consensus.py
  tests/consensus/test_consensus3.py
  tests/event/test_event_reorg.py
  tests/feature_activation/test_feature_simulation.py
  tests/p2p/test_double_spending.py
  tests/p2p/test_split_brain.py
  tests/p2p/test_sync.py
  tests/p2p/test_sync_mempool.py
  tests/p2p/test_twin_tx.py
  tests/resources/p2p/test_mining.py
  tests/resources/transaction/test_create_tx.py
  tests/resources/transaction/test_graphviz.py
  tests/resources/transaction/test_mining.py
  tests/resources/transaction/test_pushtx.py
  tests/resources/transaction/test_tx.py
  tests/resources/wallet/test_balance.py
  tests/resources/wallet/test_history.py
  tests/resources/wallet/test_send_tokens.py
  tests/resources/wallet/test_thin_wallet.py
  tests/tx/test_blockchain.py
  tests/tx/test_indexes.py
  tests/tx/test_indexes4.py
  tests/tx/test_multisig.py
  tests/tx/test_reward_lock.py
  tests/tx/test_timelock.py
  tests/tx/test_tips.py
  tests/tx/test_tokens.py
  tests/tx/test_tx.py
  tests/tx/test_tx_serialization.py
  tests/tx/test_tx_storage.py
  tests/utils.py
  tests/wallet/test_balance_update.py
  tests/wallet/test_index.py
  tests/wallet/test_wallet.py
Labels: refactor

#811 refactor(scripts): modularize script files
  hathor/transaction/scripts.py
  hathor/transaction/scripts/__init__.py
  hathor/transaction/scripts/base_script.py
  hathor/transaction/scripts/construct.py
  hathor/transaction/scripts/execute.py
  hathor/transaction/scripts/hathor_script.py
  hathor/transaction/scripts/multi_sig.py
  hathor/transaction/scripts/nano_contract_match_values.py
  hathor/transaction/scripts/opcode.py
  hathor/transaction/scripts/p2pkh.py
  tests/tx/test_scripts.py
Labels: refactor

#772 refactor: move simulator utils functions
  extras/custom_checks.sh
  hathor/cli/events_simulator/scenario.py
  hathor/simulator/tx_generator.py
  hathor/simulator/utils.py
  tests/cli/test_multisig_signature.py
  tests/cli/test_multisig_spend.py
  tests/cli/test_twin_tx.py
  tests/consensus/test_consensus.py
  tests/consensus/test_consensus2.py
  tests/consensus/test_consensus3.py
  tests/consensus/test_soft_voided.py
  tests/consensus/test_soft_voided2.py
  tests/consensus/test_soft_voided3.py
  tests/consensus/test_soft_voided4.py
  tests/event/test_event_reorg.py
  tests/others/test_init_manager.py
  tests/others/test_metrics.py
  tests/p2p/test_double_spending.py
  tests/p2p/test_split_brain.py
  tests/p2p/test_twin_tx.py
  tests/resources/test_mining_info.py
  tests/resources/transaction/test_block_at_height.py
  tests/resources/transaction/test_create_tx.py
  tests/resources/transaction/test_graphviz.py
  tests/resources/transaction/test_mempool.py
  tests/resources/transaction/test_pushtx.py
  tests/resources/transaction/test_transaction_confirmation.py
  tests/resources/transaction/test_tx.py
  tests/resources/transaction/test_utxo_search.py
  tests/resources/wallet/test_nano_contract.py
  tests/resources/wallet/test_search_address.py
  tests/resources/wallet/test_send_tokens.py
  tests/resources/wallet/test_thin_wallet.py
  tests/tx/test_accumulated_weight.py
  tests/tx/test_blockchain.py
  tests/tx/test_cache_storage.py
  tests/tx/test_indexes.py
  tests/tx/test_indexes4.py
  tests/tx/test_mining.py
  tests/tx/test_multisig.py
  tests/tx/test_prometheus.py
  tests/tx/test_reward_lock.py
  tests/tx/test_timelock.py
  tests/tx/test_tips.py
  tests/tx/test_traversal.py
  tests/tx/test_tx.py
  tests/tx/test_tx_serialization.py
  tests/tx/test_tx_storage.py
  tests/utils.py
  tests/wallet/test_balance_update.py
  tests/wallet/test_index.py
  tests/wallet/test_wallet.py
  tests/wallet/test_wallet_hd.py
Labels: refactor

#830 refactor(verification): organization and typing improvements [part 1/9]
  hathor/manager.py
  hathor/transaction/base_transaction.py
  hathor/transaction/block.py
  hathor/transaction/merge_mined_block.py
  hathor/transaction/resources/create_tx.py
  hathor/transaction/token_creation_tx.py
  hathor/transaction/transaction.py
  hathor/verification/transaction_verifier.py
  hathor/verification/verification_service.py
  poetry.lock
  pyproject.toml
  tests/tx/test_verification.py
Labels: refactor

#854 feat(sync-v2): Improve overall logging
  hathor/p2p/sync_v2/agent.py
  hathor/p2p/sync_v2/blockchain_streaming_client.py
  hathor/p2p/sync_v2/streamers.py
  hathor/p2p/sync_v2/transaction_streaming_client.py
Labels: enhancement

#856 feat(sync-v2): Stop streaming of transactions if an unexpected vertex is received
  hathor/p2p/sync_v2/transaction_streaming_client.py
Labels: enhancement

#865 refactor(sync-v2): Modify TransactionStreamingClient to process vertices asynchronously
  hathor/p2p/sync_v2/agent.py
  hathor/p2p/sync_v2/transaction_streaming_client.py
Labels: refactor

#872 fix(sync-v2): Fix issues caused by concurrent syncing peers
  hathor/p2p/sync_v2/agent.py
  hathor/p2p/sync_v2/streamers.py
  hathor/p2p/sync_v2/transaction_streaming_client.py
Labels: bug

#873 feat(sync-v2): Stop running callLater when a block is voided in handle_get_peer_block_hashes()
  hathor/p2p/sync_v2/agent.py
Labels: enhancement

#874 fix(storage): Fix wrong update to the best_block_tips_cache
  hathor/consensus/block_consensus.py
  tests/unittest.py
Labels: bug

#831 refactor(verification): refactor verify_sum [part 2/9]
  hathor/transaction/token_creation_tx.py
  hathor/verification/token_creation_transaction_verifier.py
  hathor/verification/transaction_verifier.py
Labels: refactor

#858 refactor(verification): move token info [part 2b/9]
  hathor/transaction/token_creation_tx.py
  hathor/transaction/transaction.py
  hathor/verification/token_creation_transaction_verifier.py
  hathor/verification/transaction_verifier.py
Labels: refactor

#832 refactor(verification): implement verify_minted_tokens [part 3/9]
  hathor/verification/token_creation_transaction_verifier.py
  tests/tx/test_verification.py
Labels: refactor

#847 feat(simulator): Add StopWhenSendLineMatch trigger
  hathor/simulator/trigger.py
  tests/simulation/test_trigger.py
Labels: enhancement

#876 feat(reliable-integration): change ordering to send voided txs first
  hathor/cli/events_simulator/scenario.py
  hathor/consensus/consensus.py
  hathor/transaction/base_transaction.py
  tests/event/test_event_reorg.py
  tests/event/test_event_simulation_scenarios.py
Labels: enhancement

#833 refactor(verification): remove BlockVerifier inheritance [part 4/9]
  hathor/cli/mining.py
  hathor/simulator/simulator.py
  hathor/verification/block_verifier.py
  hathor/verification/merge_mined_block_verifier.py
  hathor/verification/verification_service.py
  tests/tx/test_verification.py
Labels: refactor

#834 refactor(verification): remove TransactionVerifier inheritance [part 5/9]
  hathor/simulator/simulator.py
  hathor/verification/token_creation_transaction_verifier.py
  hathor/verification/transaction_verifier.py
  hathor/verification/verification_service.py
  tests/tx/test_verification.py
Labels: refactor
