Repository HathorNetwork/hathor-core, pull requests merged in 2023-09, with the labels that each got.

#758 refactor: use Hathor simulator on events simulator CLI
  hathor/cli/events_simulator/event_forwarding_websocket_factory.py
  hathor/cli/events_simulator/event_forwarding_websocket_protocol.py
  hathor/cli/events_simulator/events_simulator.py
  hathor/cli/events_simulator/scenario.py
  hathor/cli/events_simulator/scenarios/__init__.py
  hathor/cli/events_simulator/scenarios/only_load_events.py
  hathor/cli/events_simulator/scenarios/reorg_events.py
  hathor/cli/events_simulator/scenarios/single_chain_blocks_and_transactions_events.py
  hathor/cli/events_simulator/scenarios/single_chain_one_block_events.py
  tests/event/test_event_simulation_scenarios.py
Labels: enhancement

#756 tests: decrease tests duration
  tests/feature_activation/test_mining_simulation.py
Labels: tests

#768 refactor: move get settings [part 1]
  hathor/conf/get_settings.py
  hathor/p2p/sync_v1/agent.py
  hathor/p2p/sync_v1/downloader.py
  hathor/p2p/sync_v2/agent.py
  hathor/p2p/utils.py
  hathor/prometheus.py
  hathor/simulator/fake_connection.py
  hathor/simulator/miner/geometric_miner.py
  hathor/simulator/simulator.py
  hathor/simulator/tx_generator.py
  hathor/stratum/stratum.py
  hathor/transaction/__init__.py
  hathor/transaction/base_transaction.py
  hathor/transaction/block.py
  hathor/transaction/token_creation_tx.py
  hathor/transaction/transaction.py
  tests/tx/test_tx.py
  tests/unittest.py
Labels: refactor

#770 refactor: move get settings [part 3]
  hathor/cli/run_node.py
  hathor/p2p/resources/mining_info.py
  hathor/p2p/resources/status.py
  hathor/p2p/states/hello.py
  hathor/p2p/states/ready.py
  hathor/transaction/resources/dashboard.py
  hathor/transaction/resources/mempool.py
  hathor/transaction/resources/push_tx.py
  hathor/transaction/resources/transaction.py
  hathor/transaction/resources/utxo_search.py
  hathor/transaction/scripts.py
  hathor/transaction/storage/transaction_storage.py
  hathor/transaction/storage/tx_allow_scope.py
  hathor/transaction/util.py
  hathor/util.py
  hathor/version_resource.py
  hathor/wallet/resources/balance.py
  hathor/wallet/resources/thin_wallet/address_balance.py
  hathor/wallet/resources/thin_wallet/address_history.py
  hathor/wallet/resources/thin_wallet/address_search.py
  hathor/wallet/resources/thin_wallet/send_tokens.py
  hathor/wallet/resources/thin_wallet/token_history.py
  hathor/wallet/resources/thin_wallet/tokens.py
  hathor/wallet/util.py
Labels: refactor

#780 feat(p2p): Add ping salt and improve rtt information
  hathor/p2p/resources/status.py
  hathor/p2p/states/ready.py
  tests/p2p/test_protocol.py
Labels: enhancement

#779 refactor(verification): move vertex verification to its own service
  hathor/builder/builder.py
  hathor/builder/cli_builder.py
  hathor/manager.py
  hathor/p2p/sync_v2/agent.py
  hathor/transaction/base_transaction.py
  hathor/transaction/block.py
  hathor/transaction/token_creation_tx.py
  hathor/transaction/transaction.py
  hathor/verification/__init__.py
  hathor/verification/block_verification.py
  hathor/verification/token_creation_transaction_verification.py
  hathor/verification/transaction_verification.py
  hathor/verification/verification_service.py
  hathor/wallet/resources/send_tokens.py
  hathor/wallet/resources/thin_wallet/send_tokens.py
  tests/consensus/test_consensus.py
  tests/event/test_event_reorg.py
  tests/p2p/test_sync.py
  tests/p2p/test_sync_mempool.py
  tests/tx/test_blockchain.py
  tests/tx/test_indexes.py
  tests/tx/test_reward_lock.py
  tests/tx/test_tips.py
  tests/tx/test_tokens.py
  tests/tx/test_tx.py
  tests/tx/test_tx_storage.py
  tests/utils.py
  tests/wallet/test_balance_update.py
  tests/wallet/test_wallet.py
  tests/wallet/test_wallet_hd.py
Labels: refactor
