Repository HathorNetwork/hathor-core, pull requests merged in 2023-10, with the labels that each got.

#778 feat(wallet): Add BaseWallet.get_balance_per_address() method
  hathor/types.py
  hathor/wallet/base_wallet.py
  tests/wallet/test_balance_update.py
Labels: enhancement

#787 refactor(settings): change HathorManager to use injected settings
  hathor/builder/builder.py
  hathor/builder/cli_builder.py
  hathor/manager.py
  tests/p2p/test_get_best_blockchain.py
Labels: refactor

#794 refactor(settings): refactor genesis module
  hathor/builder/cli_builder.py
  hathor/conf/mainnet.py
  hathor/conf/mainnet.yml
  hathor/conf/settings.py
  hathor/conf/testnet.py
  hathor/conf/testnet.yml
  hathor/indexes/base_index.py
  hathor/indexes/height_index.py
  hathor/indexes/memory_height_index.py
  hathor/indexes/memory_info_index.py
  hathor/indexes/rocksdb_height_index.py
  hathor/p2p/utils.py
  hathor/simulator/simulator.py
  hathor/transaction/base_transaction.py
  hathor/transaction/genesis.py
  hathor/transaction/storage/transaction_storage.py
  hathor/transaction/transaction_metadata.py
  tests/others/fixtures/invalid_byte_hathor_settings_fixture.yml
  tests/others/fixtures/invalid_features_hathor_settings_fixture.yml
  tests/others/fixtures/missing_hathor_settings_fixture.yml
  tests/others/fixtures/valid_hathor_settings_fixture.yml
  tests/others/test_hathor_settings.py
  tests/p2p/test_split_brain.py
  tests/resources/wallet/test_thin_wallet.py
  tests/tx/test_block.py
  tests/tx/test_indexes2.py
  tests/tx/test_mining.py
  tests/tx/test_stratum.py
  tests/tx/test_tx_storage.py
  tests/unittest.py
  tests/utils.py
Labels: refactor

#796 refactor(verification): create vertex verifiers [part 1/5]
  hathor/builder/builder.py
  hathor/builder/cli_builder.py
  hathor/verification/block_verification.py
  hathor/verification/block_verifier.py
  hathor/verification/merge_mined_block_verifier.py
  hathor/verification/token_creation_transaction_verifier.py
  hathor/verification/transaction_verification.py
  hathor/verification/transaction_verifier.py
  hathor/verification/verification_service.py
  hathor/verification/vertex_verifier.py
Labels: refactor

#782 feat(p2p): relay all recently-seen peers for neighbors
  hathor/p2p/manager.py
  hathor/p2p/peer_id.py
  hathor/p2p/protocol.py
  hathor/p2p/resources/status.py
  hathor/p2p/states/ready.py
  hathor/p2p/sync_v1/agent.py
  tests/p2p/test_protocol.py
Labels: enhancement

#815 test(simulation): Fix flaky test test_many_miners_since_beginning
  hathor/simulator/fake_connection.py
  tests/simulation/test_simulator.py
Labels: tests

#816 test(sync): Improve test_sync_rotate to prevent false positives
  tests/p2p/test_sync_enabled.py
Labels: tests

#821 tests: fix flaky log test
  tests/feature_activation/test_bit_signaling_service.py
Labels: tests

#822 fix(mining): Fix block template not checking for MAX_FUTURE_TIMESTAMP_ALLOWED
  hathor/exception.py
  hathor/manager.py
  hathor/simulator/miner/geometric_miner.py
  tests/tx/test_mining.py
Labels: bug

#824 tests(verification): implement tests to improve refactor reliability
  tests/tx/test_verification.py
Labels: tests

#797 refactor(verification): move verification methods signatures [part 2/5]
  hathor/cli/mining.py
  hathor/stratum/stratum.py
  hathor/transaction/resources/create_tx.py
  hathor/verification/block_verifier.py
  hathor/verification/merge_mined_block_verifier.py
  hathor/verification/token_creation_transaction_verifier.py
  hathor/verification/transaction_verifier.py
  hathor/verification/verification_service.py
  hathor/verification/vertex_verifier.py
  tests/simulation/test_simulator.py
  tests/tx/test_genesis.py
  tests/tx/test_tx.py
  tests/tx/test_tx_deserialization.py
  tests/wallet/test_wallet_hd.py
Labels: refactor

#798 refactor(verification): move block-only verification methods [part 3/5]
  hathor/transaction/block.py
  hathor/transaction/merge_mined_block.py
  hathor/verification/block_verifier.py
  hathor/verification/merge_mined_block_verifier.py
  tests/tx/test_verification.py
Labels: refactor

#799 refactor(verification): move transaction-only verification methods [part 4/5]
  hathor/cli/mining.py
  hathor/transaction/token_creation_tx.py
  hathor/transaction/transaction.py
  hathor/verification/token_creation_transaction_verifier.py
  hathor/verification/transaction_verifier.py
  tests/tx/test_verification.py
Labels: refactor

#800 refactor(verification): finish moving all verification methods [part 5/5]
  hathor/simulator/simulator.py
  hathor/simulator/verification.py
  hathor/transaction/base_transaction.py
  hathor/transaction/block.py
  hathor/transaction/transaction.py
  hathor/verification/block_verifier.py
  hathor/verification/transaction_verifier.py
  hathor/verification/vertex_verifier.py
  tests/tx/test_tx.py
  tests/tx/test_verification.py
  tests/wallet/test_wallet_hd.py
Labels: refactor

#829 refactor(sync-v2): Refactor sync_v2 agent to hold (block_height, block_id) information in an internal namedtuple
  hathor/p2p/sync_v2/agent.py
  tests/p2p/test_get_best_blockchain.py
  tests/p2p/test_sync.py
  tests/simulation/test_simulator.py
  tests/unittest.py
Labels: refactor

#828 fix(feature-activation): add missing metadata migration
  hathor/feature_activation/bit_signaling_service.py
  hathor/manager.py
  hathor/transaction/storage/migrations/add_feature_activation_bit_counts_metadata.py
  hathor/transaction/storage/transaction_storage.py
Labels: bug
