Repository HathorNetwork/hathor-core, pull requests merged in 2023-07, with the labels that each got.

#691 chore: update mypy, mypy-zope, and pydantic
  poetry.lock
  pyproject.toml
Labels: dependencies

#696 tests: implement new PubSub tests
  tests/pubsub/test_pubsub2.py
Labels: tests

#706 fix(event-queue): fix event simulator scenario parsing
  hathor/cli/events_simulator/events_simulator.py
Labels: bug

#732 refactor(sync-v2): improve deferreds handling
  hathor/p2p/sync_v2/manager.py
Labels: refactor

#686 feat: add get-best-blockchain capability
  hathor/conf/settings.py
  hathor/manager.py
  hathor/p2p/messages.py
  hathor/p2p/protocol.py
  hathor/p2p/states/hello.py
  hathor/p2p/states/ready.py
  hathor/p2p/states/utils.py
  hathor/transaction/block.py
  hathor/transaction/storage/transaction_storage.py
  hathor/types.py
  tests/p2p/test_get_best_blockchain.py
  tests/p2p/test_protocol.py
Labels: enhancement

#738 refactor(event-queue): improve event ordering
  hathor/consensus/consensus.py
  tests/event/test_event_reorg.py
  tests/event/test_event_simulation_scenarios.py
  tests/utils.py
Labels: enhancement
