Repository HathorNetwork/hathor-core, pull requests merged in 2023-08, with the labels that each got.

#744 fix(event-queue): improve memory usage during the load phase
  hathor/event/event_manager.py
  hathor/utils/iter.py
Labels: bug

#704 feat: add best_blockchain in /status payload
  hathor/p2p/resources/status.py
  hathor/p2p/states/ready.py
  hathor/p2p/states/utils.py
  hathor/p2p/utils.py
  tests/p2p/test_get_best_blockchain.py
Labels: enhancement

#753 chore: improve miner simulator flakiness
  hathor/simulator/miner/geometric_miner.py
  hathor/simulator/trigger.py
  tests/feature_activation/test_mining_simulation.py
Labels: enhancement, tests

#694 chore: improve pubsub
  hathor/builder/cli_builder.py
  hathor/cli/run_node.py
  hathor/consensus/consensus.py
  hathor/debug_resources.py
  hathor/p2p/sync_v1/agent.py
  hathor/p2p/sync_v2/streamers.py
  hathor/pubsub.py
  hathor/reactor/__init__.py
  hathor/reactor/reactor.py
  hathor/reactor/reactor_core_protocol.py
  hathor/reactor/reactor_protocol.py
  hathor/reactor/reactor_tcp_protocol.py
  hathor/reactor/reactor_time_protocol.py
  hathor/simulator/clock.py
  hathor/simulator/simulator.py
  hathor/stratum/stratum.py
  hathor/transaction/block.py
  hathor/transaction/storage/transaction_storage.py
  hathor/transaction/transaction.py
  hathor/transaction/transaction_metadata.py
  hathor/util.py
  hathor/utils/zope.py
  tests/event/websocket/test_factory.py
  tests/others/test_metrics.py
  tests/p2p/test_connections.py
  tests/pubsub/test_pubsub2.py
  tests/test_memory_reactor_clock.py
  tests/unittest.py
Labels: enhancement, refactor
