Repository HathorNetwork/hathor-core, pull requests merged in 2024-10, with the labels that each got.

#1140 fix: event handling of txs with custom scripts
  hathor/cli/events_simulator/scenario.py
  hathor/event/model/event_data.py
  tests/event/test_event_simulation_scenarios.py
Labels: bug

#1139 fix: removed txs from test wallet
  hathor/cli/events_simulator/scenario.py
  hathor/consensus/consensus.py
  hathor/event/model/event_data.py
  hathor/wallet/base_wallet.py
  tests/tx/test_reward_lock.py
Labels: bug

#1146 refactor(static-metadata): undo migration of feature_states to static metadata
  hathor/transaction/static_metadata.py
  hathor/transaction/storage/rocksdb_storage.py
  hathor/transaction/transaction_metadata.py
  tests/feature_activation/test_feature_service.py
  tests/feature_activation/test_feature_simulation.py
Labels: refactor

#1151 refactor(p2p): simplify factory [part 1/5]
  hathor/builder/builder.py
  hathor/builder/cli_builder.py
  hathor/cli/events_simulator/events_simulator.py
  hathor/event/websocket/factory.py
  hathor/manager.py
  hathor/metrics.py
  hathor/p2p/factory.py
  hathor/p2p/manager.py
  hathor/p2p/protocol.py
  hathor/p2p/states/hello.py
  hathor/simulator/simulator.py
  hathor/transaction/block.py
  hathor/transaction/storage/__init__.py
  hathor/transaction/storage/traversal.py
  tests/cli/test_events_simulator.py
  tests/event/websocket/test_factory.py
  tests/others/test_metrics.py
  tests/p2p/test_bootstrap.py
  tests/poa/test_poa_verification.py
  tests/tx/test_cache_storage.py
  tests/unittest.py
Labels: refactor

#1157 fix(benchmark): fix benchmark CI after bencher update
  .github/workflows/pr_benchmarks.yml
Labels: bug

#1148 refactor(settings): change wallets and reward lock to use injected settings
  hathor/builder/builder.py
  hathor/conf/settings.py
  hathor/manager.py
  hathor/reward_lock/reward_lock.py
  hathor/simulator/simulator.py
  hathor/transaction/storage/transaction_storage.py
  hathor/verification/transaction_verifier.py
  hathor/wallet/base_wallet.py
  hathor/wallet/hd_wallet.py
  hathor/wallet/wallet.py
Labels: refactor

#1153 refactor: move can_validate_full method [part 2/8]
  hathor/manager.py
  hathor/p2p/sync_v2/agent.py
  hathor/p2p/sync_v2/blockchain_streaming_client.py
  hathor/transaction/base_transaction.py
  hathor/transaction/storage/transaction_storage.py
Labels: refactor

#572 feat(consensus): Change meta.score and meta.accumulated_weight to int type
  hathor/consensus/block_consensus.py
  hathor/consensus/transaction_consensus.py
  hathor/event/model/event_data.py
  hathor/manager.py
  hathor/mining/block_template.py
  hathor/transaction/base_transaction.py
  hathor/transaction/resources/decode_tx.py
  hathor/transaction/resources/transaction.py
  hathor/transaction/resources/transaction_confirmation.py
  hathor/transaction/storage/migrations/change_score_acc_weight_metadata.py
  hathor/transaction/storage/transaction_storage.py
  hathor/transaction/transaction_metadata.py
  hathor/util.py
  hathor/utils/weight.py
  hathor/wallet/resources/send_tokens.py
  hathor/wallet/resources/thin_wallet/send_tokens.py
  tests/event/test_base_event.py
  tests/event/test_event_simulation_scenarios.py
  tests/event/test_tx_metadata.py
  tests/event/websocket/test_protocol.py
  tests/resources/transaction/test_mining.py
  tests/resources/transaction/test_transaction_confirmation.py
  tests/tx/test_accumulated_weight.py
  tests/tx/test_blockchain.py
  tests/tx/test_indexes.py
  tests/tx/test_mining.py
  tests/tx/test_tx_storage.py
  tests/utils.py
Labels: enhancement

#1154 refactor(vertex-handler): remove p2p_manager dependency [part 1/8]
  hathor/builder/builder.py
  hathor/builder/cli_builder.py
  hathor/manager.py
  hathor/p2p/sync_v1/agent.py
  hathor/p2p/sync_v2/agent.py
  hathor/p2p/sync_v2/blockchain_streaming_client.py
  hathor/p2p/sync_v2/mempool.py
  hathor/profiler/cpu.py
  hathor/transaction/storage/transaction_storage.py
  hathor/vertex_handler/vertex_handler.py
Labels: refactor
