Repository HathorNetwork/hathor-core, pull requests merged in 2024-08, with the labels that each got.

#998 chore: update dependencies
  hathor/p2p/manager.py
  hathor/p2p/utils.py
  hathor/wallet/resources/thin_wallet/send_tokens.py
  hathor/wallet/wallet.py
  hathor/websocket/protocol.py
  poetry.lock
  pyproject.toml
Labels: dependencies

#1098 chore: flake.nix creating a devshell with all fullnode dependencies needed to run the fullnode
  .envrc
  .gitignore
  flake.lock
  flake.nix
Labels: enhancement

#1014 refactor(metadata): move metadata attributes to static metadata [part 2/12]
  hathor/builder/resources_builder.py
  hathor/consensus/poa/poa_block_producer.py
  hathor/feature_activation/feature_service.py
  hathor/feature_activation/resources/feature.py
  hathor/manager.py
  hathor/mining/block_template.py
  hathor/p2p/resources/mining_info.py
  hathor/p2p/resources/status.py
  hathor/p2p/sync_v2/agent.py
  hathor/p2p/sync_v2/streamers.py
  hathor/stratum/stratum.py
  hathor/transaction/base_transaction.py
  hathor/transaction/block.py
  hathor/transaction/resources/decode_tx.py
  hathor/transaction/resources/mining.py
  hathor/transaction/resources/transaction.py
  hathor/transaction/static_metadata.py
  hathor/transaction/storage/cache_storage.py
  hathor/transaction/storage/memory_storage.py
  hathor/transaction/storage/migrations/migrate_static_metadata.py
  hathor/transaction/storage/migrations/remove_first_nop_features.py
  hathor/transaction/storage/rocksdb_storage.py
  hathor/transaction/storage/transaction_storage.py
  hathor/transaction/transaction.py
  hathor/transaction/transaction_metadata.py
  hathor/util.py
  hathor/verification/block_verifier.py
  hathor/verification/transaction_verifier.py
  hathor/verification/verification_service.py
  hathor/vertex_handler/vertex_handler.py
  hathor/wallet/resources/send_tokens.py
  hathor/wallet/resources/thin_wallet/send_tokens.py
  tests/feature_activation/test_feature_service.py
  tests/feature_activation/test_feature_simulation.py
  tests/feature_activation/test_mining_simulation.py
  tests/p2p/test_sync.py
  tests/poa/test_poa.py
  tests/poa/test_poa_verification.py
  tests/resources/feature/test_feature.py
  tests/resources/transaction/test_mining.py
  tests/resources/transaction/test_pushtx.py
  tests/resources/transaction/test_tx.py
  tests/resources/transaction/test_utxo_search.py
  tests/resources/wallet/test_send_tokens.py
  tests/tx/test_block.py
  tests/tx/test_blockchain.py
  tests/tx/test_cache_storage.py
  tests/tx/test_indexes.py
  tests/tx/test_reward_lock.py
  tests/tx/test_tokens.py
  tests/tx/test_tx.py
  tests/tx/test_tx_storage.py
  tests/tx/test_verification.py
  tests/wallet/test_wallet.py
  tests/wallet/test_wallet_hd.py
Labels: refactor

#1016 refactor(metadata): pre-refactors for migrating feature states to static metadata [part 3/12]
  hathor/builder/builder.py
  hathor/builder/cli_builder.py
  hathor/builder/resources_builder.py
  hathor/feature_activation/bit_signaling_service.py
  hathor/feature_activation/feature_service.py
  hathor/feature_activation/model/feature_info.py
  hathor/feature_activation/model/feature_state.py
  hathor/feature_activation/resources/feature.py
  hathor/transaction/__init__.py
  hathor/transaction/static_metadata.py
  hathor/transaction/storage/rocksdb_storage.py
  hathor/verification/block_verifier.py
  hathor/verification/verification_service.py
  hathor/vertex_handler/vertex_handler.py
  tests/feature_activation/test_bit_signaling_service.py
  tests/feature_activation/test_feature_service.py
  tests/feature_activation/test_feature_simulation.py
  tests/resources/feature/test_feature.py
  tests/tx/test_verification.py
Labels: refactor
