Repository HathorNetwork/hathor-core, pull requests merged in 2024-05, with the labels that each got.

#1026 refactor: remove SimpleMemoryStorage and refactor DAA
  hathor/daa.py
  hathor/manager.py
  hathor/simulator/simulator.py
  hathor/stratum/stratum.py
  hathor/transaction/storage/simple_memory_storage.py
  hathor/verification/block_verifier.py
  hathor/verification/vertex_verifier.py
  hathor/verification/vertex_verifiers.py
  tests/simulation/test_simulator.py
  tests/tx/test_genesis.py
Labels: refactor

#1029 fix: catch update_reward_lock_metadata exceptions
  hathor/vertex_handler/vertex_handler.py
Labels: bug

#944 docs(README): update and organize readme and supplementary documentation of the repository
  README.md
  SECURITY.md
  docs/README.md
  docs/debugging.md
  docs/developing.md
  docs/event-queue-feature.md
  docs/legacy/Makefile
  docs/legacy/conf.py
  docs/legacy/conflict-resolution.rst
  docs/legacy/glossary.rst
  docs/legacy/images/syncing-example.png
  docs/legacy/images/syncing-example.txt
  docs/legacy/index.rst
  docs/legacy/make.bat
  docs/legacy/quickstart.rst
  docs/legacy/ref/crypto.rst
  docs/legacy/ref/index.rst
  docs/legacy/ref/p2p.rst
  docs/legacy/ref/pubsub.rst
  docs/legacy/ref/transaction.rst
  docs/legacy/ref/wallet.rst
  docs/legacy/sync.rst
  docs/legacy/tx-maleability.rst
  docs/metadocs-openapi-redoc-usage-guide.md
  docs/rocksdb-indexes-feature.md
Labels: documentation

#1033 feat(cli): Add --log-vertex-bytes for debugging
  hathor/builder/cli_builder.py
  hathor/cli/run_node.py
  hathor/cli/run_node_args.py
  hathor/vertex_handler/vertex_handler.py
Labels: enhancement

#1040 fix(log): correctly handle errors when logging events
  hathor/cli/util.py
Labels: bug
